### ISSUE TITLE
When you copy paste a list of emails it overflows over the input area

### ISSUE THREAD

**Issue by Shkotsky** [axisj/react-multi-email#106]
When you copy paste a list of emails (it doesn't need to be too big) it overflows over the input area.
![overflowBug](https://user-images.githubusercontent.com/35734717/208147365-44812710-f5dc-4a44-8e87-383bad0f6d2a.png)

The solution is simple all it needs is `flexWrap: inherit` in  here `dist/es6/ReactMultiEmail.js` in the element where it has the `data-labels` class next to `display: inherit`

**Comment by thomasJang** [comment]
Thank you so much for letting me know the problem, I hope you have a happy end of the year.

**Comment by Shkotsky** [comment]
Thank you for the fast response 😃, and have a great year 🎊
