### ISSUE TITLE
Is it possible / (slash) to be delimiter of emails?

### ISSUE THREAD

**Issue by Shkotsky** [axisj/react-multi-email#109]
For example: mark@google.com/david@yahoo.com/gene@facebook.com

**Comment by thomasJang** [comment]
You can use delimiter prop in 1.0.5 Thank you

**Comment by Shkotsky** [comment]
Thanks for the fast response, but is it possible for the delimiter to be an array of strings so the user has multiple options?
@thomasJang 

> delimiter={["/", ",", ";"]}

**Comment by Shkotsky** [comment]
That was my mistake it works as expected 😄  you are a lifesaver! Thank you very much ❤️ 

So the others don't make the same mistake 😄
> This is the right way delimiter={[/, ,, ;]}
