### ISSUE TITLE
Bug - Backspace triggers validateEmail handler

### ISSUE THREAD

**Issue by samatar26** [axisj/react-multi-email#140]
Hello 👋 

I have a usecase where I only want the "Enter" key to trigger submission/validateEmail handler. I've tried:
- Setting 13 as the delimiter
- Not setting a delimiter

But it looks like the "Enter" and "Backspace" key both always trigger submission/validation. Is this a bug?

It would also be really nice if we could somehow pass the key that was pressed to the validateEmail handler. But I guess this wouldn't be as useful if we delimiter would work as intended.

Thank you for looking into this!

**Comment by thomasJang** [comment]
You can use on 1.0.14

**Comment by samatar26** [comment]
Thanks sooooo much!!

One other thing I've noticed is that when I click outside of the input, the validateEmail handler also triggers. Is there a way you know of that I can prevent this?

**Comment by thomasJang** [comment]
It is probably validating as the blur event occurs.

Let's see if exception handling for blur event is possible.
