### ISSUE TITLE
Not working value change

### ISSUE THREAD

**Issue by Bttlg** [axisj/react-multi-email#153]
My initial value: ["test@gmail.com", "test5@gmail.com"]

I get emails from excel file...
Result: ["smileofhades9@gmail.com", "adsfasf@gmail.com", "aslkj@gmail.com"]

But don't work re-render getLabel function. Still showing old value...  ["test@gmail.com", "test5@gmail.com"]
My state value changed. ["test@gmail.com", "test5@gmail.com"] ->  ["smileofhades9@gmail.com", "adsfasf@gmail.com", "aslkj@gmail.com"]

It was working fine two days ago.

**Comment by thomasJang** [comment]
Hello. Please show me the reaction-multi-email usage code. Thanks

**Comment by Bttlg** [comment]
MyState structure: 
const [participants, setParticipants] = useState({
     participant1: ["smileofhades9@gmail.com"], 
     participant2: null
})

It's my code setting code: 
const setImportedEmailToParticipants = (importedEmails) => {
    let newParts = {
      ...participants,
      [`${importParticipantKey}`]: importedEmails,
    };
    setParticipants(newParts);
  };

<ReactMultiEmail
                  emails={participants?.[key] || []}
                  onChange={(_emails) => {
                    setParticipantErrors(null);
                    handleEmailChange(_emails, key);
                  }}
                  allowDuplicate={true}
                  autoFocus={true}
                  getLabel={(email, index, removeEmail) => {
                    return (
                      <div data-tag key={index}>
                        <div data-tag-item>{email}</div>
                        {key !== "participant1" && (
                          <span
                            data-tag-handle
                            onClick={() => removeEmail(index)}
                          >
                            ×
                          </span>
                        )}
                      </div>
                    );
                  }}
                />

**Comment by thomasJang** [comment]
```js
setParticipants({...newParts});
```

If the key value in the object is changed, JS does not recognize it as a new value.
I think it will probably work if I use it as above.
If possible, I think it's better not to use the email value as an object key.

**Comment by Bttlg** [comment]
It's not working. I aspirant this way.  

it's my state...
const [changedEmails, setChangedEmails] = useState([]);

setChangedEmails([...importedEmails]); or setChangedEmails(importedEmails);

config:
emails={changedEmails}

It's my result. But still re-render not working. 
![Screenshot 2023-08-14 at 09 32 03](https://github.com/axisj/react-multi-email/assets/87216121/f615cada-e5f3-4b86-813d-ce3d0c794f08)
Do you have any ideas?

**Comment by 134130** [comment]
Hi @Bttlg , your intent is not working because `react-multi-email` is just using `emails` props with `useState` which only initializing the values.

If you want to change emails, you should re-render the `react-multi-email` now.

@thomasJang I think we can support dynamic props changing with `useEffect` hook. How do you think about this?
```js

// propsEmails: string[] | undefined
const [emails, setEmails] = React.useState<string[]>(() => initialEmailAddress(propsEmails));

// Add hook
useEffect(() => {
  setEmails(propsEmails || []);
}, [propsEmails]);
```

**Comment by thomasJang** [comment]
Thank you very much, @134130 

And @Bttlg  I'm sorry I didn't check the problem exactly. 
There is a problem with the code, so it is being modified. It will be fixed soon.

**Comment by HyeongSeoku** [comment]
@Bttlg is the issue has been resolved ?
