### ISSUE TITLE
Getting undefined error when write "," first time in the empty input (In latest version)

### ISSUE THREAD

**Issue by Ajaykhavas** [axisj/react-multi-email#166]
I am using latest version of react-multi-email (**1.0.18**), In the email input first time when input is empty and write the "**,**" showing error (TypeError: Cannot read properties of undefined (reading 'trim')) as shown in below image. This issue is in the latest version as I changed the version to (**1.0.11**) it is working fine.

<img width="314" alt="image" src="https://github.com/axisj/react-multi-email/assets/90394942/4fd45d1f-92d9-4f26-895b-54656287d4af">

**Comment by hovelopin** [comment]
Thanks for providing the error, we will check it out quickly and leave a comment

**Comment by hovelopin** [comment]
we fixed that issue so you can use avaliable in the latest version **1.0.19**

**Comment by Ajaykhavas** [comment]
Great, yes now it's working in the latest version 1.019
