### ISSUE TITLE
Placeholder not showing when focus on input

### ISSUE THREAD

**Issue by Ajaykhavas** [axisj/react-multi-email#168]
When we click in the multi email input (Focus) the placeholder is not showing it should show, if we are doing autofocus then when we show input instantly it focuses but the placeholder is not showing, that should be fix !

<img width="458" alt="image" src="https://github.com/axisj/react-multi-email/assets/90394942/3a940605-ae96-4cca-9147-2943faacf340">

**Comment by Ajaykhavas** [comment]
I re-installed the library but still getting the issue!

**Comment by thomasJang** [comment]
now you can use react-multi-email@1.0.20
thank you.

**Comment by Ajaykhavas** [comment]
Yes that's working, but getting another issue when I enter the value as shown in the image and click outside the value will be removed. That is  correct. If I write normal value like ("dsasadasd") then it shows validation error but for the values like I entered in image it is removing.

<img width="371" alt="image" src="https://github.com/axisj/react-multi-email/assets/90394942/eb5ef145-b0ca-4048-8768-8ca8d065c8bd">

**Comment by Ajaykhavas** [comment]
Yes now working, Thanks!
