### ISSUE TITLE
Study Progress 

### ISSUE THREAD

**Issue by IMHOJEONG** [axisj/react-multi-email#32]
## To do List

- [x] Markdown Editing 
- [x] Study Next.js
- [x] familarize React hooks
- [x] Typescript-in-5-minutes
- [x] Git : Rebase, fast-forward, merge
- [x] js : debounce, throttle
- [ ] Jest => Now Studying!

### Next.js

[Next.js tutorial to Korean](https://www.notion.so/Next-js-9e97d6af53594777aca56724be1ae127)

![1](https://user-images.githubusercontent.com/11308147/68181188-cf27f800-ffd9-11e9-90cb-ee61fec825db.png)

### TypeScript in 5 minutes
[TypeScript in 5 minutes](https://www.notion.so/TypeScript-f1f3c4e3c7104e778f78ec53d1df0388)

## Markdown Editing
[Markdown Editing](https://www.notion.so/Markdown-47891d1c3e7d4953ac88699663e6e378)

## Git : rebase & merge & fast-forward
[Git](https://www.notion.so/Git-caaf069ecbc64b8ca8a1913fc8e9ba74)

## JS : Debouncing & throttling
[Debounce And Throttle](https://www.notion.so/Debouncing-throttling-882328e993db46ad95c271524092a203)

## React Hooks
[React Hooks](https://github.com/IMHOJEONG/React-Hooks)

## Jest -> Studying!!!!
[Jest Tutorial Study repo](https://github.com/IMHOJEONG/React-Hooks)

**Comment by thomasJang** [comment]
Good job
